serial_no: 1
cam_name: "cam1"
yaml_url: "package://mcptam/calibrations/camera2.yaml"
exposure_time: 30000
rect_left: 200
rect_top: 200
rect_width: 4096
rect_height: 3072
image_data_format: "XI_MONO8"
